### ISSUE TITLE
Access letter

### ISSUE THREAD

**Issue by Virginie-T** [FAC7/SharePlan#14]
As a client, I want to see to the letters that has been sent out.

**Comment by eleanorreem** [comment]
When the report is 'waiting for review' that is available in a 'dropbox' where patients or stakeholders who are assigned editing rights can edit a version of the document.

**Comment by eleanorreem** [comment]
Changes in the document are tracked??

**Comment by EMiliosStar** [comment]
documents can be commented at the bottom facebook style

**Comment by Virginie-T** [comment]
Create new issue with better description, see #73
