### ISSUE TITLE
Which Emailiing system

### ISSUE THREAD

**Issue by eleanorreem** [FAC7/SharePlan#25]
Twillio ?
Messagebird?
Any suggestions?

**Comment by katbow** [comment]
@Virginie-T check this out as well. I can't comment right now but I will look into both over the weekend and it can be a focus for someone Monday

**Comment by katbow** [comment]
No longer using a text messaging system for notifications. 

If notifications are added in, then it will be email notifications. We can consider mail gun or send grid
@Virginie-T @eleanorreem @oturnermajor
