### ISSUE TITLE
Add client - modal

### ISSUE THREAD

**Issue by eleanorreem** [FAC7/SharePlan#33]

**Comment by otajor** [comment]
Info needs to change on form and fix the name field that requires an email.

**Comment by katbow** [comment]
Yes - this needs to be combined with #32 in a way. The clinician needs to be able to Add a client and a list of recipients which need to receive a letter.

**Comment by katbow** [comment]
Also for this and #32 we need to add a remove function for if a new line for letter topic/recipient is added by mistake.
