### ISSUE TITLE
write up data structure

### ISSUE THREAD

**Issue by eleanorreem** [FAC7/SharePlan#36]

**Comment by katbow** [comment]
@andrewMacmurray it'd be great if you could get on this. deadlines tomorrow.

**Comment by andrewMacmurray** [comment]
#slackers

**Comment by otajor** [comment]
![screen shot 2016-05-24 at 15 33 59](https://cloud.githubusercontent.com/assets/13705650/15507829/07580c34-21c5-11e6-9981-b75729e15f89.png)

**Comment by otajor** [comment]
This is now also in the wiki, see https://github.com/FAC7/SharePlan/wiki/Database-Structure
