### ISSUE TITLE
letter object data structure for table ?

### ISSUE THREAD

**Issue by eleanorreem** [FAC7/SharePlan#55]
How do we want the letter listing to look? What are the table headers? 

``` javascript
{
  letters: [
    {
      topic: 'Assessment results',
      recipients: [
        'School'
      ] ,
     correspondence: [
      'patient', 'patient\'s mum', 'school'
     ] , 
     status: 'pending',
     due: '10/11/16'
   }
 ]
}
```

recipients = the ones receiving this letter in the post
correspondence = not sure what to call this, but these are the people who are getting notified of the letter coming the post to the recipients

Do we want a letter id? 

This is as far as I can understand it.

**Comment by Virginie-T** [comment]
@eleanorreem  I think it looks good but we will have to think about how it will be in Postgres and how to access it.

**Comment by katbow** [comment]
@oturnermajor @Virginie-T this structure is laid out in https://github.com/FAC7/SharePlan/pull/70 correct?

**Comment by otajor** [comment]
@katbow not explicitly. The format for letters is going to be:

``` javascript
[{
  topic: 'some topic',
  recipient: 'Katherine',
  patient_id: 'jfewah8493',
  status: 'sent',
  date_created: '2016-01-28'
},
...]
```

i.e. an array of objects. You will be able to get letters for a particular patient or for all patients associated with a certain clinician.

**Comment by katbow** [comment]
@oturnermajor sorry I was unclear. I meant there was _a_ data structure laid out for this, not that it was the the same as the initial layout. This good to be closed then?

**Comment by otajor** [comment]
Yes, as far as I can see. Closing now.
