### ISSUE TITLE
Dropbox link when waiting for review

### ISSUE THREAD

**Issue by Virginie-T** [FAC7/SharePlan#73]
As a Clinician,
When I change the status of a letter to "waiting for review", I want to be able to provide a dropbox link to my Letter in order for the patient to edit/comment on it.

**Comment by EMiliosStar** [comment]
This may not be dropbox itself as we do not use dropbox for security reasons.
The link would be to a 'page' where they can review the report.
And leave comments

**Comment by katbow** [comment]
Letter upload is no longer a priority
